### ISSUE TITLE
Add Default SignedOut page

### ISSUE THREAD

**Issue by simbaja** [pomerium/pomerium#861] opened 2020-06-09 15:40 UTC
**Is your feature request related to a problem? Please describe.**
**Describe the solution you'd like**

Add a default signout redirect url (e.g. /.pomerium/signed_out).  This can be a landing zone when no redirect is supplied by the user.

**Comment by desimone** [comment] 2020-08-27 21:19
Duplicate of #1324

**Closed by desimone** 2020-08-27 21:19 UTC
