### ISSUE TITLE
proxy returns `stream terminated by RST_STREAM with error code: PROTOCOL_ERROR` while trying to authorize

### ISSUE THREAD

**Issue by chauffer** [pomerium/pomerium#420] opened 2019-12-04 11:29 UTC
## What happened?
500 - Internal Server Error when trying to access a proxied service

## What did you expect to happen?
Forwarding

## How'd it happen?
1. Go to proxied domain
2. Log in with Google
3. 500

## What's your environment like?

- Pomerium version: 0.5.1

- Environment: Kubernetes
Manifests:
```---
apiVersion: v1
kind: Service
metadata:
  name: pomerium
spec:
  ports:
    - port: 80
      name: http
      targetPort: 443
    - name: metrics
      port: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomerium
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: pomerium
        image: pomerium
        args:
        - --config=/etc/pomerium/config.yaml
        env:
        - {name: INSECURE_SERVER, value: "true"}
        - {name: POMERIUM_DEBUG, value: "true"}
        - {name: AUTHENTICATE_SERVICE_URL, value: https://pomerium-authn.$(DOMAIN)}
        - {name: FORWARD_AUTH_URL, value: https://pomerium-fwd.$(DOMAIN)}
        - {name: IDP_PROVIDER, value: google}
        - name: COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: pomerium
              key: cookie-secret
        - name: SHARED_SECRET
          valueFrom:
            secretKeyRef:
              name: pomerium
              key: shared-secret
        - name: IDP_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: pomerium
              key: idp-client-id
        - name: IDP_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: pomerium
              key: idp-client-secret
        - name: IDP_SERVICE_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: pomerium
              key: idp-service-account
        ports:
          - containerPort: 443
            name: http
          - containerPort: 9090
            name: metrics
        livenessProbe:
          httpGet:
            path: /ping
            port: 443
        readinessProbe:
          httpGet:
            path: /ping
            port: 443
        volumeMounts:
        - mountPath: /etc/pomerium/
          name: config
      volumes:
      - name: config
        configMap:
          name: pomerium
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pomerium
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - pomerium-authn.$(DOMAIN)
    - pomerium-fwd.$(DOMAIN)
    secretName: pomerium-tls
  rules:
    - host: pomerium-authn.$(DOMAIN)
      http:
        paths:
          - path: /
            backend:
              serviceName: pomerium
              servicePort: 80
    - host: pomerium-fwd.$(DOMAIN)
      http:
        paths:
          - path: /
            backend:
              serviceName: pomerium
              servicePort: 80
```

## What's your config.yaml?

```config.yaml
policy: 
  - from: https://test-nginx.cs-eng-apps-europe-west3.gcp.infra.csol.cloud
    to: http://httpbin.pomerium/
    allowed_domains:
      - container-solutions.com
```

## What did you see in the logs?

```logs
11:23AM ERR http-error error="rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR" X-Forwarded-For=["10.156.0.9"] X-Forwarded-Host=["test-nginx.cs-eng-ops-europe-west3.gcp.infra.csol.cloud"] X-Forwarded-Port=["443"] X-Forwarded-Proto=["https"] X-Real-Ip=["10.156.0.9"] http-code=500 http-message="rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR" ip=10.40.0.6 req_id=d7e56771-0e2c-a7de-4518-25e7267da9ed user_agent="Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
11:23AM DBG proxy: AuthorizeSession error="rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR" X-Forwarded-For=["10.156.0.9"] X-Forwarded-Host=["test-nginx.cs-eng-ops-europe-west3.gcp.infra.csol.cloud"] X-Forwarded-Port=["443"] X-Forwarded-Proto=["https"] X-Real-Ip=["10.156.0.9"] ip=10.40.0.6 req_id=d7e56771-0e2c-a7de-4518-25e7267da9ed user_agent="Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
11:23AM DBG http-request X-Forwarded-For=["10.156.0.9"] X-Forwarded-Host=["test-nginx.cs-eng-ops-europe-west3.gcp.infra.csol.cloud"] X-Forwarded-Port=["443"] X-Forwarded-Proto=["https"] X-Real-Ip=["10.156.0.9"] duration=5.869461 email=email@container-solutions.com group=<groups> host=test-nginx.cs-eng-ops-europe-west3.gcp.infra.csol.cloud ip=10.40.0.6 method=GET path=/ req_id=d7e56771-0e2c-a7de-4518-25e7267da9ed service=all size=8150 status=500 user_agent="Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
```

## Additional context

I get this error both with all-in-one mode and by deploying the services separately. I have been messing with GRPC ports etc. before opening this issue but I could not find what the problem is.
It seems like the proxy wants to talk to authorize over gRPCs but that is not available in `INSECURE_SERVER` mode

**Comment by desimone** [comment] 2019-12-06 04:09
@chauffer 

This is the first time I've seen this error. But I think you are on the right track that this has to do with gRPC failing to connect over insecure sockets.

Does setting `grpc_insecure`/ `GRPC_INSECURE` to [true](https://www.pomerium.io/configuration/#shared-settings) solve the issue? That said, I am really surprised to see any gRPC related errors in all in one mode which defaults to insecure mode over localhost's socket. Are there any other configuration details in `config.yaml`? Your config above seems reasonable to me.

**Comment by chauffer** [comment] 2019-12-06 10:41
Thanks @desimone, same error, these are the startup logs:

```{"level":"warn","time":"2019-12-06T10:40:11Z","message":"config: insecure mode enabled"}
10:40AM INF cmd/pomerium version=v0.5.1+1b7b916
10:40AM DBG add domain domain=container-solutions.com route=test-nginx.cs-eng-ops-europe-west3.gcp.infra.csol.cloud
10:40AM WRN internal/grpcutil: insecure server addr=:5443
10:40AM INF proxy/clients: grpc with insecure addr=localhost:5443
10:40AM INF internal/httputil: http server started addr=:443```

**Comment by desimone** [comment] 2019-12-06 20:24
Does setting `AUTHORIZE_SERVICE_URL` to `127.0.0.1:5443` work? 

I'm far from a kubernetes expert but is there any chance that _localhost_ isn't actually an alias to loopback? All of this traffic should be happening local to the container which is why that error is so perplexing.

**Comment by chauffer** [comment] 2019-12-06 22:19
By setting it to that, this is what I get
```
{"level":"fatal","error":"config: options from viper validation error config: bad authorize-url 127.0.0.1:5443 : parse 127.0.0.1:5443: first path segment in URL cannot contain colon","time":"2019-12-06T22:14:08Z","message":"cmd/pomerium"}
```

By setting it to `http://127.0.0.1:5443`, I get the same error

`localhost` does resolve to `127.0.0.1` in Kubernetes

**Comment by desimone** [comment] 2019-12-06 22:21
\cc @travisgroth any ideas why this config would be failing in k8s? 🙃

**Comment by chauffer** [comment] 2019-12-11 07:53
@desimone Any idea even for a possible workaround? This is blocking our deployment of pomerium :(

**Comment by desimone** [comment] 2019-12-11 20:45
@chauffer Does a clean install using the helm-chart work?

**Comment by chauffer** [comment] 2019-12-11 20:51
The helm chart does not support insecure. I based my initial install off the helm chart adding INSECURE_SERVER params and it failed, to make the minimum reproducible failure I brought everything in one service. It feels to me this is an issue with pomerium proxy-authorize connection using the wrong protocol, I haven't had a chance to look at the code yet. I believe a clean install using helm would work.

**Comment by desimone** [comment] 2019-12-11 21:24
> The helm chart does not support insecure which I would like to use here. 

Got it. 

> I based my initial install off the helm chart adding INSECURE_SERVER params and it failed, to make the minimum reproducible failure I brought everything in one service. It feels to me this is an issue with pomerium proxy-authorize connection using the wrong protocol, I haven't had a chance to look at the code yet. I believe a clean install using helm would work.

That's my speculation as well. 

Your configuration looks good to me; I run something very like it on my home lab but using docker-compose not Kubernetes so my hunch is that this is Kubernetes specific. This is a bit tricky to debug for me at the moment as I am away on vacation and can't replicate your configuration exactly. 

An idea... What happens if you try adding an additional service port?

```yaml
...
    - port: 5443
      name: grpc
...
```

**Comment by chauffer** [comment] 2019-12-12 08:17
Services in Kubernetes are only for exposing the ports to other containers in the cluster, there will be no difference in how the container networking is setup for communication within localhost by changing the service, could you post your docker-compose? maybe I can spot the difference... 😄

**Comment by desimone** [comment] 2019-12-12 19:01
@chauffer 

Good thought. Here it is: https://gist.github.com/desimone/90761373bbbb1468893e8bd55acc8f73

**Comment by chauffer** [comment] 2019-12-12 19:55
thanks! I will give it a try to see if I can figure out something, at first
glance you are setting some things in policy.yaml which I set in env vars,
maybe that could be a difference? I'll see

**Comment by chauffer** [comment] 2019-12-13 15:08
For the record, we tried also 0.4.0, 0.4.1, 0.5.0, 0.5.2, and master, with the same error (although with new UI on master!)

**Comment by desimone** [comment] 2019-12-14 00:22
@chauffer I see you are using `forward-auth` but I don't see the ingress definitions for forwarding. Do you mind adding those?

**Comment by chauffer** [comment] 2019-12-14 00:26
Currently it's just defined, but forward auth is not being used, the
test-nginx is a simple ingress pointing to pomerium-proxy directly. Does
setting forward auth URL braak "normal" proxying through pomerium?

**Comment by desimone** [comment] 2019-12-14 00:36
> Does setting forward auth URL braak "normal" proxying through pomerium?

No it should have no effect. 

I had another idea. If you explicitly set the protocol of the port (and healthcheck probes) to `TCP` does that fix the issue? 

https://github.com/pomerium/pomerium/blob/11843c56114650475888aa5a2fa22f08b9782ab8/docs/configuration/examples/kubernetes/pomerium-authorize.yml#L35-L37

**Comment by travisgroth** [comment] 2019-12-15 12:57
Hi @chauffer - What is your Kubernetes network configuration like?  I just tried something really similar outside of kubernetes and I'm not able to reproduce.   I think this is specific to your cluster and how the pod network is set up.

I put an SSL proxy (https://github.com/suyashkumar/ssl-proxy) in front of pomerium built from HEAD:

```bash
ssl-proxy -from 127.0.0.1:443
```

and ran this config:

```yaml
address: :80
debug: true
insecure_server: true
authenticate_service_url: https://authenticate.lan.beyondcorp.org
shared_secret: XXXXXXX
cookie_secret: XXXXXXX
idp_provider: "google"
idp_client_id: XXXXXXX
idp_client_secret: XXXXXXX
metrics_address: 127.0.0.1:9090
policy:
  - from: https://grafana.lan.beyondcorp.org
    to: http://httpbin.org
    allowed_domains:
      - beyondcorp.org

```

That should simulate an ingress controller in front of pomerium in 'all' mode.  Both grafana and authenticate point to localhost.  I'm leveraging the default for authorize to connect/listen on localhost:

```
{"level":"warn","addr":":5443","time":"2019-12-15T07:52:50-05:00","message":"internal/grpcutil: insecure server"}
{"level":"info","addr":"localhost:5443","time":"2019-12-15T07:52:50-05:00","message":"proxy/clients: grpc with insecure"}
```

**Comment by chauffer** [comment] 2019-12-15 13:19
@desimone 
>I had another idea. If you explicitly set the protocol of the port (and healthcheck probes) to TCP does that fix the issue?

Setting these things does not change any networking in Kubernetes

@travisgroth it's a GKE cluster, with nothing special with regards to networking, I do not see any way that kubernetes would be in the way here.
Have you tried applying my manifest in a kubernetes cluster and trying to reproduce that way? [K3s](https://k3s.io) should be fine.

I understand a similar setup might be working for you, but I am in no way closer to solving this deployment and I am not sure how to help you debug it.

**Comment by travisgroth** [comment] 2019-12-15 21:02
>I understand a similar setup might be working for you

>it's a GKE cluster, with nothing special with regards to networking, I do not see any way that kubernetes would be in the way here, especially when running all-in-one!

My point here is that isolating the config of insecure + insecure_grpc + all-in-one, which is admittedly **not** heavily tested, does seem to work with a normal network stack.  That leaves the kubernetes specific stuff which, I agree, shouldn't remotely be an issue on simple configurations.  However, indications seem to be that there is something about how you are deploying pomerium or the environment you are deploying it into.

GKE has a few modes of operation, including Istio, network policy, CNI etc.  I am not deeply familiar with all of them, but perhaps the way they alter the environment has something to do with the problem you're seeing.  

>Have you tried applying my manifest in a kubernetes cluster and trying to reproduce that way? K3s should be fine.

Yes, with some tweaks to make them deployable, I was able to get up and running on a docker-for-desktop local cluster with nginx ingress.  SSL completely terminated at the ingress; definitely not seeing the same error.  I didn't make any changes that would have impacted networking or effective config.

I suggest checking `kubectl describe` or `kubectl get -o yaml` from the pods to see network config, actual deployed container spec, etc.  My guess is the answer is somewhere in there.

**Comment by strideynet** [comment] 2019-12-17 10:08
I'm also experiencing this on my GKE cluster with a similar setup. We have Istio installed as well which I'm tempted to blame for the problem.

```
    services: all
    address: :8080
    insecure_server: true
    grpc_address: :5443
    grpc_insecure: true
    authorize_service_url: http://127.0.0.1:5443
    authenticate_service_url: https://pomerium.cudo.org
    idp_provider: google
    idp_provider_url: https://accounts.google.com
    policy:
    - from: https://grafana.cudo.org
      to: http://grafana.default.svc:80
      allow_websockets: true
```

**Comment by chauffer** [comment] 2019-12-17 10:47
@strideynet Don't be so quick to blame istio, we don't have it deployed and see the same error :)

>I suggest checking kubectl describe or kubectl get -o yaml from the pods to see network config, actual deployed container spec, etc. My guess is the answer is somewhere in there.
@travisgroth unfortunately not, I have spent quite a bit of time troubleshooting (on the GKE cluster) before opening the issue.

I am unable to at the moment, but what I will do early next year is try to reproduce this error in k3s if we still haven't figured it out by then

**Comment by travisgroth** [comment] 2019-12-17 11:32
@strideynet I'm curious what happens if you change grpc port from the default:

```
grpc_address: :5444
authorize_service_url: http://localhost:5444
grpc_insecure: true
```

**Comment by strideynet** [comment] 2019-12-17 11:49
@travisgroth That seems to be working!!!

```
    address: :8080
    insecure_server: true
    grpc_address: :5444
    grpc_insecure: true
    authorize_service_url: http://pomerium.default.svc.cluster.local:5444
    authenticate_service_url: https://pomerium.cudo.org
    idp_provider: google
    idp_provider_url: https://accounts.google.com
```

In my k8s I have configured the service to expose GRPC and the HTTP port.

**Comment by travisgroth** [comment] 2019-12-17 14:11
>In my k8s I have configured the service to expose GRPC and the HTTP port.

It should work via loopback as well.  If you're going through a service, you might as well use a `Deployment` dedicated to the authorize service like we have in the helm chart.  I'm not clear on the use case you have but our [recommended configuration](https://www.pomerium.io/docs/reference/production-deployment.html) is mirrored in the helm chart.  

It appears something specific to GKE networking and/or Istio is putting another (probably) gRPC service that _is_ secure on `5443` into your pod's network namespace.  Istio/envoy certainly could be doing this.  

I recall `5443` being a pseudo-default in the gRPC world, but I could be mistaken.  I bet if you set `grpc_secure: true` with the default port set, you'd get an error indicating the Authorize service wasn't on that endpoint or it wasn't speaking http2.

For an additional bullet point, I just deployed test manifests to a non-Istio GKE cluster using vpc native and pomerium is functioning.  @chauffer if you aren't running Istio, you must have something else going on that has the same result.

Anyway, I'm fairly certain this is a deployment issue.  Going to close it.

**Comment by chauffer** [comment] 2019-12-17 16:06
We get the same error by setting `GRPC_ADDRESS=:6767` and `AUTHORIZE_SERVICE_URL=http://localhost:6767`.

Once again, we do not have anything special wrt. networking, but I guess we are on our own.

**Comment by travisgroth** [comment] 2019-12-18 00:03
Given we can't reproduce inside or outside of a vanilla kubernetes cluster, I'm not sure how to help further.  Pomerium does appear to function correctly in this config with the right settings based on several tests.  If you can provide further detail that indicates a bug in Pomerium, I'm happy to reopen.  There's just nothing to go on here.  It appears to be something about your deployment and config that isn't reflected in what you've posted.

If _all_ ports are returning that error, your situation sounds even stranger.  I used your manifests as a basis for my kubernetes testing and had no issues.  I also haven't been able to even simulate the problem, since all-in-one makes some assumptions during config validation.

Have you tried this?
```yaml
grpc_address: :5444
authorize_service_url: http://localhost:5443
```

**Comment by mircea-cosbuc** [comment] 2019-12-19 15:18
Did some debugging on this one and it seems like setting a `SharedKey` through the `SHARED_SECRET` in the all-in-one setup triggers this issue. Allowing `pomerium` to generate one at runtime seems to work. I'll debug it further, but maybe you have some insight into why it would happen?

**Comment by desimone** [comment] 2019-12-19 16:45
@mircea-cosbuc Very interesting and honestly a bit surprising! In this context, `shared_secret` is used to mutually authenticate gRPC connections at the request level so any unexpected token is causing an error. Out of curiosity, do you still have the error you saw / shared key you used?   It's surprising in particular because we assert that the key is 32 bytes. 

https://github.com/pomerium/pomerium/blob/a29ae6428fcdb1f073e42d751d5ee15008fa4390/authorize/authorize.go#L14-L23

**Comment by travisgroth** [comment] 2019-12-20 02:02
https://github.com/grpc/grpc-go/issues/1888 likely related 🤦‍♂ 

Okay! I was able to reproduce by forcing a newline onto the end of the base64 encoded `shared_secret` string.  Like so:

```
shared_secret: |
    bmVRejhVRlNXMENXb2tQb0xEQ2tza3NNc0tWS2oydAo=

cookie_secret: XXXXX
```  

In the proxy we validate the key: https://github.com/pomerium/pomerium/blob/11843c56114650475888aa5a2fa22f08b9782ab8/proxy/proxy.go#L42

and use the standard lib's decode: https://github.com/pomerium/pomerium/blob/11843c56114650475888aa5a2fa22f08b9782ab8/internal/cryptutil/encrypt.go#L22

It appears you can decode a base64 string like `bmVRejhVRlNXMENXb2tQb0xEQ2tza3NNc0tWS2oydAo=\n` without error and it will simply return the 32byte encoded value.  While Authorize checks the length of this as posted above, Proxy doesn't and then uses the original value passed in from user options.  This is then attached as a header with a newline and we get the very unhelpful protocol error message from grpc.

It was very difficult to introduce this in the normal yaml, but the Secret in kubernetes base64 wraps _that_ value and could obscure it fairly easily.

We should be able to protect against this a little better, especially since the low level error isn't obvious.

**Comment by travisgroth** [comment] 2019-12-20 03:08
@mircea-cosbuc @chauffer I have #427 open that should at least surface this better.  If you could take it for a spin and make sure (a) this was your issue (b) this build catches it, we'd appreciate it.

**Comment by mircea-cosbuc** [comment] 2019-12-20 08:31
@travisgroth Thanks for looking into it. I did try it with your branch and indeed this catches the whitespace issue at startup. This was indeed the issue on my side.

**Comment by chauffer** [comment] 2019-12-20 10:27
Thanks a lot!

FYI @mircea-cosbuc and I are colleagues so we are working on the same cluster

**Comment by travisgroth** [comment] 2019-12-20 11:19
Great.  Thanks for the feedback.

**Closed** 2019-12-20 11:20 UTC
Labels: deployment
