### ISSUE TITLE
cache: potential memory leak

### ISSUE THREAD

**Issue by whs** [pomerium/pomerium#1496] opened 2020-10-08 01:16 UTC
I believe pomerium-cache has a memory leak:

![Screen Shot 2563-10-08 at 8 08 49 AM](https://user-images.githubusercontent.com/345483/95403824-88efbd00-093d-11eb-9782-2de70c67f7d9.png)

I have Kubernetes memory cap at 1GB, so it hit the limit and keep crashing.

I think there should be about < 50 active users of hundreds of directory users.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): https://github.com/wongnai/pomerium master (2364da14c81c9945b6098906bbbedcbef32919ba plus my 2 PR)
- Pomerium in HA mode (one of each service run in standalone, in Kubernetes), although 1 of each. Databroker backend is Elasticache Redis
- Using forward proxy auth

## What's your config.yaml?

```jsonnet
		AUTOCERT: 'false',
		TIMEOUT_READ: '60s',
		AUTHENTICATE_SERVICE_URL: 'https://' + gatewayHost,
		FORWARD_AUTH_URL: 'https://' + forwardAuthHost,
		JWT_CLAIMS_HEADERS: 'email,groups,user',
		AUTHORIZE_SERVICE_URL: 'http://pomerium-authorize:3000',
		CACHE_SERVICE_URL: 'http://pomerium-cache:3000',
		INSECURE_SERVER: 'true',
		GRPC_INSECURE: 'true',
		METRICS_ADDRESS: ':9000',
		TRACING_PROVIDER: 'jaeger',
		TRACING_SAMPLE_RATE: '0.1',
		TRACING_JAEGER_AGENT_ENDPOINT: services.jaeger(namespace),
```

Also

- SHARED_SECRET
- IDP_SERVICE_ACCOUNT
- IDP_REFRESH_DIRECTORY_TIMEOUT=5m
- IDP_REFRESH_DIRECTORY_INTERVAL=10m
- IDP_PROVIDER_URL=https://accounts.google.com
- IDP_PROVIDER=google
- IDP_CLIENT_ID 
- IDP_CLIENT_SECRET 
- DATABROKER_STORAGE_TYPE=redis
- DATABROKER_STORAGE_CONNECTION_STRING
- DATABROKER_STORAGE_CA_FILE
- COOKIE_SECRET
- policies (in config.yaml)
- idp_request_params

All of those env keys are provided to all pods

**Comment by travisgroth** [comment] 2020-10-12 14:52
Hi @whs - I'm not able to reproduce this behavior currently.  Our master branch now has a pprof endpoint.  Would you be able to roll your cache instance up to the latest [`master` image](https://hub.docker.com/layers/pomerium/pomerium/master/images/sha256-b6c8d96da188f45dcc64a18709e308d528a1e8314dcc387b191df48c633095a0?context=repo) and see if the behavior continues?

If so:

```bash
PORT=$(kubectl logs pomerium-cache-[POD HASH] | head -30 | grep "HTTP server started" | jq '.port' -r)
port-forward pomerium-cache-[POD HASH] 6060:$PORT &
curl http://localhost:6060/debug/pprof/heap | gzip -c > /tmp/heap.gzip
kill %1
```

and share the heap profile.

**Comment by whs** [comment] 2020-10-20 23:56
Seems like the redis pool is leaking? https://upload.disroot.org/r/zvsnfA9u#yWX1aacRmI0iKXE2Vu1FByDnNXPrqjYJEwwpOEsKb1w=

**Comment by travisgroth** [comment] 2021-02-23 19:47
We've done a significant number of changes to the databroker/cache code since this issue was reported and were never able to reproduce.  If this is still an issue with the latest release, please let us know.  Closing for now.

**Closed by travisgroth** 2021-02-23 19:47 UTC
Labels: NeedsInvestigation, WaitingForInfo
