### ISSUE TITLE
403 Forbidden from proxied kubernetes when using group authorization and google idp

### ISSUE THREAD

**Issue by pmahoney** [pomerium/pomerium#2076] opened 2021-04-09 03:29 UTC
## What happened?

I've configured pomerium as a kubernetes proxy. To confirm that everything works, I created a RoleBinding to my individual user, and was able to list pods, for example:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: specific-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: pmahoney@example.com
```

With the above RoleBinding deleted and the following in place:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: group
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: mygroup@example.com
```

I get 403 Forbidden.

From the kubernetes cluster logs (not sure if these are from apiserver or some other component), I can see the successful and failed requests.

The successful request includes:

```
{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC: allowed by RoleBinding \"specific-user/default\" of ClusterRole \"view\" to User \"pmahoney@example.com\""}

impersonatedUser | {"username":"pmahoney@example.com","groups":["<lots of comma-separated groups>,mygroup@example.com,<more comma-separated groups>","system:authenticated"]}
```

The failed request includes:

```
{"authorization.k8s.io/decision":"forbid","authorization.k8s.io/reason":""}

impersonatedUser | {"username":"pmahoney@example.com","groups":["<lots of comma-separated groups>,mygroup@example.com,<more comma-separated groups>","system:authenticated"]}
```

I notice the "groups" array includes only two entries: a single string that's a comma-separated list, and a second string "system:authenticated".  It seems like my multiple groups are being passed to kubernetes as a single (very wide) group name instead of as multiple individual groups?

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): docker image `pomerium/pomerium:v0.13.2`

## What's your config.yaml?

Using google provider with a service account that can get group membership.

```config.yaml
idp_provider: google

policy:
  - from: https://kubernetes.external.example.com
    to: https://kubernetes.internal.example.com
    allowed_domains: ["example.com"]
    kubernetes_service_token: xxx

# (as env vars)
    IDP_CLIENT_ID       = xxx
    IDP_CLIENT_SECRET   = xxx
    IDP_SERVICE_ACCOUNT = xxx
```

**Comment by calebdoxsey** [comment] 2021-04-09 14:14
Hi @pmahoney,

Thanks for the detailed bug report. This issue was recently fixed in master https://github.com/pomerium/pomerium/pull/2051 and should be released with 0.14. If possible do you want to try this version to see if it fixes the issue for you?

For context the issue is that envoy coalesces multiple headers into a single comma-separated header. This is valid by the spec, but Kubernetes can't handle it (they have good reasons for this, LDAP groups can have commas in them). We were at an impasse and a bit out of our depth to try and address the underlying problem in either project, so we came up with an alternative solution (implemented in the above PR).

**Comment by pmahoney** [comment] 2021-04-09 15:44
That's great news.

I did try it out, but may have done something wrong...  (maybe some cache is stale and needs to be cleared?) I'm using the pomerium helm chart @ version 16.0.4. I simply set `image.tag` to `git-6d1d2bec` which is also the version of `pomerium-cli` I have locally.

`kubectl get pods` shows this:

`error: yaml: line 11: mapping values are not allowed in this context` (without popping up the browser login)

and (slightly sanitized) pomerium logs look like this (prefixed with kubernetes pod id)

```
pomerium-authorize-6944b8bdd8-p7xpf {"level":"info","service":"authorize","request-id":"618384d1-5f6e-48db-8713-2968e61bba43","check-request-id":"b1bdfcfc-1442-44a5-bbc3-57ce8b199aa6","method":"GET","path":"/api","host":"kubernetes-api.example.com","query":"","allow":false,"status":401,"message":"login required","user":"","email":"","databroker_server_version":15774548127032614615,"databroker_record_version":43,"time":"2021-04-09T15:26:19Z","message":"authorize check"}
pomerium-authenticate-855c5b76b-5jz7m {"level":"info","X-Forwarded-For":["x.x.x.x"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"ip":"127.0.0.1","user_agent":"kubectl/v1.18.6 (darwin/amd64) kubernetes/dff82dc","referer":"https://kubernetes-api.example.com/api?timeout=32s","request-id":"49502401-9908-4f98-8207-9f829109977e","error":"Bad Request: square/go-jose: error in cryptographic primitive","time":"2021-04-09T15:26:20Z","message":"authenticate: session load error"}
pomerium-proxy-5dc5b8749-cwbn2 {"level":"info","service":"envoy","upstream-cluster":"","method":"GET","authority":"kubernetes-api.example.com","path":"/api","user-agent":"kubectl/v1.18.6 (darwin/amd64) kubernetes/dff82dc","referer":"","forwarded-for":"x.x.x.x","request-id":"b1bdfcfc-1442-44a5-bbc3-57ce8b199aa6","duration":6.280553,"size":5,"response-code":302,"response-code-details":"ext_authz_denied","time":"2021-04-09T15:26:20Z","message":"http-request"}
pomerium-authorize-6944b8bdd8-g4bg8 {"level":"info","service":"authorize","request-id":"00f87d63-e912-45a3-83f5-084904ae6489","check-request-id":"032c2ac9-866c-4549-975a-2cba7ff9fb7d","method":"GET","path":"/api","host":"kubernetes-api.example.com","query":"","allow":false,"status":401,"message":"login required","user":"","email":"","databroker_server_version":15774548127032614615,"databroker_record_version":40,"time":"2021-04-09T15:26:21Z","message":"authorize check"}
pomerium-authenticate-855c5b76b-5jz7m {"level":"info","X-Forwarded-For":["x.x.x.x"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"ip":"127.0.0.1","user_agent":"kubectl/v1.18.6 (darwin/amd64) kubernetes/dff82dc","referer":"https://kubernetes-api.example.com/api?timeout=32s","request-id":"e2b4bf45-4e7d-408e-b6a1-7e687b7a86aa","error":"Bad Request: square/go-jose: error in cryptographic primitive","time":"2021-04-09T15:26:21Z","message":"authenticate: session load error"}
pomerium-authenticate-855c5b76b-5jz7m {"level":"info","service":"envoy","upstream-cluster":"pomerium-control-plane-http","method":"GET","authority":"authenticate.example.com","path":"/.pomerium/sign_in","user-agent":"kubectl/v1.18.6 (darwin/amd64) kubernetes/dff82dc","referer":"https://kubernetes-api.example.com/api","forwarded-for":"x.x.x.x","request-id":"49502401-9908-4f98-8207-9f829109977e","duration":1.043454,"size":918,"response-code":302,"response-code-details":"via_upstream","time":"2021-04-09T15:26:21Z","message":"http-request"}
pomerium-authenticate-855c5b76b-5jz7m {"level":"info","service":"envoy","upstream-cluster":"pomerium-control-plane-http","method":"GET","authority":"authenticate.example.com","path":"/.pomerium/sign_in","user-agent":"kubectl/v1.18.6 (darwin/amd64) kubernetes/dff82dc","referer":"https://kubernetes-api.example.com/api","forwarded-for":"x.x.x.x","request-id":"e2b4bf45-4e7d-408e-b6a1-7e687b7a86aa","duration":0.750702,"size":918,"response-code":302,"response-code-details":"via_upstream","time":"2021-04-09T15:26:21Z","message":"http-request"}
pomerium-authorize-6944b8bdd8-g4bg8 {"level":"info","service":"authorize","request-id":"2d2f4f7b-5536-42ee-825c-d12d1bea892f","check-request-id":"24359059-a6be-405e-9860-529e68c7acba","method":"GET","path":"/api","host":"kubernetes-api.example.com","query":"","allow":false,"status":401,"message":"login required","user":"","email":"","databroker_server_version":15774548127032614615,"databroker_record_version":40,"time":"2021-04-09T15:26:21Z","message":"authorize check"}
pomerium-authenticate-855c5b76b-5jz7m {"level":"info","X-Forwarded-For":["x.x.x.x"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"ip":"127.0.0.1","user_agent":"kubectl/v1.18.6 (darwin/amd64) kubernetes/dff82dc","referer":"https://kubernetes-api.example.com/api?timeout=32s","request-id":"f19786c8-352e-4230-bbe8-65ffea6117c4","error":"Bad Request: square/go-jose: error in cryptographic primitive","time":"2021-04-09T15:26:21Z","message":"authenticate: session load error"}
pomerium-proxy-5dc5b8749-cwbn2 {"level":"info","service":"envoy","upstream-cluster":"","method":"GET","authority":"kubernetes-api.example.com","path":"/api","user-agent":"kubectl/v1.18.6 (darwin/amd64) kubernetes/dff82dc","referer":"","forwarded-for":"x.x.x.x","request-id":"24359059-a6be-405e-9860-529e68c7acba","duration":4.6839,"size":5,"response-code":302,"response-code-details":"ext_authz_denied","time":"2021-04-09T15:26:21Z","message":"http-request"}
pomerium-proxy-5dc5b8749-cwbn2 {"level":"info","service":"envoy","upstream-cluster":"","method":"GET","authority":"kubernetes-api.example.com","path":"/api","user-agent":"kubectl/v1.18.6 (darwin/amd64) kubernetes/dff82dc","referer":"","forwarded-for":"x.x.x.x","request-id":"032c2ac9-866c-4549-975a-2cba7ff9fb7d","duration":5.867916,"size":5,"response-code":302,"response-code-details":"ext_authz_denied","time":"2021-04-09T15:26:21Z","message":"http-request"}
pomerium-authenticate-855c5b76b-5jz7m {"level":"info","service":"envoy","upstream-cluster":"pomerium-control-plane-http","method":"GET","authority":"authenticate.example.com","path":"/.pomerium/sign_in","user-agent":"kubectl/v1.18.6 (darwin/amd64) kubernetes/dff82dc","referer":"https://kubernetes-api.example.com/api","forwarded-for":"x.x.x.x","request-id":"f19786c8-352e-4230-bbe8-65ffea6117c4","duration":0.783815,"size":918,"response-code":302,"response-code-details":"via_upstream","time":"2021-04-09T15:26:22Z","message":"http-request"}
pomerium-authorize-6944b8bdd8-p7xpf {"level":"info","service":"authorize","request-id":"3ccf8c6b-ff74-4765-94f7-633e15ccf851","check-request-id":"2a49382b-51dc-4ce2-ad1e-eb39ddc0de11","method":"GET","path":"/api","host":"kubernetes-api.example.com","query":"","allow":false,"status":401,"message":"login required","user":"","email":"","databroker_server_version":15774548127032614615,"databroker_record_version":43,"time":"2021-04-09T15:26:22Z","message":"authorize check"}
pomerium-authenticate-855c5b76b-5jz7m {"level":"info","X-Forwarded-For":["x.x.x.x"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"ip":"127.0.0.1","user_agent":"kubectl/v1.18.6 (darwin/amd64) kubernetes/dff82dc","referer":"https://kubernetes-api.example.com/api?timeout=32s","request-id":"45b31add-0e7c-4830-8a84-9446f1c3f5ab","error":"Bad Request: square/go-jose: error in cryptographic primitive","time":"2021-04-09T15:26:22Z","message":"authenticate: session load error"}
pomerium-authorize-6944b8bdd8-p7xpf {"level":"info","service":"authorize","request-id":"4f0fa194-2726-488a-a6b4-93ab2cb04a15","check-request-id":"dc426504-4fe1-40db-8ac3-e5f7fdced313","method":"GET","path":"/api","host":"kubernetes-api.example.com","query":"","allow":false,"status":401,"message":"login required","user":"","email":"","databroker_server_version":15774548127032614615,"databroker_record_version":43,"time":"2021-04-09T15:26:22Z","message":"authorize check"}
pomerium-proxy-5dc5b8749-cwbn2 {"level":"info","service":"envoy","upstream-cluster":"","method":"GET","authority":"kubernetes-api.example.com","path":"/api","user-agent":"kubectl/v1.18.6 (darwin/amd64) kubernetes/dff82dc","referer":"","forwarded-for":"x.x.x.x","request-id":"2a49382b-51dc-4ce2-ad1e-eb39ddc0de11","duration":5.834626,"size":5,"response-code":302,"response-code-details":"ext_authz_denied","time":"2021-04-09T15:26:22Z","message":"http-request"}
pomerium-proxy-5dc5b8749-cwbn2 {"level":"info","service":"envoy","upstream-cluster":"","method":"GET","authority":"kubernetes-api.example.com","path":"/api","user-agent":"kubectl/v1.18.6 (darwin/amd64) kubernetes/dff82dc","referer":"","forwarded-for":"x.x.x.x","request-id":"dc426504-4fe1-40db-8ac3-e5f7fdced313","duration":4.290367,"size":5,"response-code":302,"response-code-details":"ext_authz_denied","time":"2021-04-09T15:26:22Z","message":"http-request"}
pomerium-authenticate-855c5b76b-5jz7m {"level":"info","X-Forwarded-For":["x.x.x.x"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"ip":"127.0.0.1","user_agent":"kubectl/v1.18.6 (darwin/amd64) kubernetes/dff82dc","referer":"https://kubernetes-api.example.com/api?timeout=32s","request-id":"c1b21a84-e527-43ba-9635-b1d03d3f421b","error":"Bad Request: square/go-jose: error in cryptographic primitive","time":"2021-04-09T15:26:22Z","message":"authenticate: session load error"}
pomerium-authenticate-855c5b76b-5jz7m {"level":"info","service":"envoy","upstream-cluster":"pomerium-control-plane-http","method":"GET","authority":"authenticate.example.com","path":"/.pomerium/sign_in","user-agent":"kubectl/v1.18.6 (darwin/amd64) kubernetes/dff82dc","referer":"https://kubernetes-api.example.com/api","forwarded-for":"x.x.x.x","request-id":"45b31add-0e7c-4830-8a84-9446f1c3f5ab","duration":0.770922,"size":918,"response-code":302,"response-code-details":"via_upstream","time":"2021-04-09T15:26:23Z","message":"http-request"}
pomerium-authenticate-855c5b76b-5jz7m {"level":"info","service":"envoy","upstream-cluster":"pomerium-control-plane-http","method":"GET","authority":"authenticate.example.com","path":"/.pomerium/sign_in","user-agent":"kubectl/v1.18.6 (darwin/amd64) kubernetes/dff82dc","referer":"https://kubernetes-api.example.com/api","forwarded-for":"x.x.x.x","request-id":"c1b21a84-e527-43ba-9635-b1d03d3f421b","duration":0.814842,"size":918,"response-code":302,"response-code-details":"via_upstream","time":"2021-04-09T15:26:23Z","message":"http-request"}
```

Couple things that jump out are "Bad Request: square/go-jose: error in cryptographic primitive" from pomerium-authenticate and the empty user and email fields `login required","user":"","email":""` (which could be normal? I'm not too familiar with what's "normal" in the logs).

**Comment by calebdoxsey** [comment] 2021-04-09 15:58
@pmahoney I think our credentials cache isn't handling reauthenticating well. Could you try removing:

* Linux: `~/.config/pomerium-cli/cache/*` 
* MacOS: `~/Library/Application Support/pomerium-cli/cache/*` (I think)

(there was a change to how sessions were encrypted, so it should've invalidated the old token and tried to get a new one, but doesn't seem to be doing that)

**Comment by pmahoney** [comment] 2021-04-09 16:05
Deleting my local pomerium-cli cache got me farther (browser auth popped up).

Now pomerium-proxy is complaining `http: proxy error: x509: certificate signed by unknown authority`. Could configuration of that have changed?  Looking... 

(previously i was providing the cert via `tls_custom_ca` but I also had to set `tls_server_name`, and that stuff may have been changed recently in https://github.com/pomerium/pomerium/issues/1166)

**Comment by calebdoxsey** [comment] 2021-04-09 16:08
@pmahoney this may be a bug with the recent kubernetes change we made. We're re-proxying through our go control plane and it may not be handling all the TLS options properly. You're using `tls_custom_ca` and `tls_server_name`? Any other TLS options?

**Comment by calebdoxsey** [comment] 2021-04-09 16:11
We're definitely not using `tls_custom_ca` properly. Only the one at the global level. I'll work on a fix for that.

**Comment by pmahoney** [comment] 2021-04-09 16:12
Just those two for tls. Here's the config snippet (this is an EKS cluster on AWS if that matters; I don't have control over the TLS cert on kubernetes API, and it has only `Subject: CN=kubernetes`)

```
  - allowed_domains:
    - example.com
    from: https://kubernetes-api.example.com
    to: https://xxx.eks.amazonaws.com
    kubernetes_service_account_token: xxx
    tls_custom_ca: base64-encode(xxx)
    tls_server_name: kubernetes
```

**Comment by pmahoney** [comment] 2021-04-09 18:45
It worked!

I tested the image from https://github.com/pomerium/pomerium/pull/2077 (docker image git-8924b1a5), and I no longer get the certificate error, and the group-based RoleBinding works as expected.

Thanks for your help, that was extremely fast turnaround :)

**Closed** 2021-04-09 19:10 UTC
