### ISSUE TITLE
Forward auth redirect loops and 500s

### ISSUE THREAD

**Issue by ChipWolf** [pomerium/pomerium#690] opened 2020-05-11 23:25 UTC
We deploy Pomerium via Helm, it's behind ingress-nginx, we use GSuite for our IDP.

Our Helm Release:
```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pomerium
  namespace: pomerium
spec:
  releaseName: pomerium
  chart:
    repository: https://helm.pomerium.io
    name: pomerium
    version: 8.5.5
  valuesFrom:
    - secretKeyRef:
        name: pomerium-values
  values:
    ingress:
      annotations:
        kubernetes.io/ingress.class: "nginx"
        kubernetes.io/ingress.allow-http: "false"
        external-dns.alpha.kubernetes.io/hostname: |
          forwardauth.example.com,
          authorize.example.com,
          authenticate.example.com
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/proxy-buffer-size: "16K"
    forwardAuth:
      enabled: true
    service:
      type: NodePort
    config:
      rootDomain: example.com
    operator:
      enabled: true
```

Additional Helm values stored in secret `pomerium-values`:
```yaml
config:
  sharedSecret: #snip
  cookieSecret: #snip
authenticate:
  idp:
    provider: google
    url: https://accounts.google.com
    clientID: #snip
    clientSecret: #snip
    serviceAccount: #snip
```

An ingress configured for Pomerium auth:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: app1.example.com
    ingress.pomerium.io/allowed_domains: '["example.com"]'
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-signin: https://forwardauth.example.com/?uri=$scheme://$host$request_uri
    nginx.ingress.kubernetes.io/auth-url: https://forwardauth.example.com/verify?uri=$scheme://$host$request_uri
  name: app1
  namespace: app
spec:
  rules:
  - host: app1.example.com
    http:
      paths:
      - backend:
          serviceName: app-service
          servicePort: 80
        path: /
```

Attempting to hit any of our apps which are hooked up to Pomerium results in these errors and the client being served with a 500. Immediately prior to this, we were suffering from redirect loops with `proxy/authorize: deny` and `backend refresh failed` errors, after deployment without any config changes we are now seeing this new behaviour.

Current errors:
```
pomerium-proxy-57b7486fbc-l6gxh:pomerium {"level":"warn","X-Forwarded-For":["35.123.123.241"],"X-Forwarded-Host":["forwardauth.example.com"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Original-Method":["GET"],"X-Original-Url":["http://app1.example.com/sw.js"],"X-Real-Ip":["35.123.123.241"],"X-Sent-From":["nginx-ingress-controller"],"ip":"192.168.22.9","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36","referer":"https://app1.example.com/sw.js","req_id":"8db5c120-11fc-e5b3-6337-7a9062f34cd1","error":"proxy: backend refresh failed: {\"Status\":401,\"Error\":\"Unauthorized: rpc error: code = Unknown desc = cache.grpc.Get error: autocache: get 427dd2648869df90 failed: autocache: empty ctx for id: 427dd2648869df90\",\"RequestID\":\"226a56b8-ac77-6b2f-04bb-3eaa4f513c67\"}\n","time":"2020-05-11T23:19:17Z","message":"proxy: refresh failed"}

pomerium-authenticate-669586595f-tqhn6:pomerium {"level":"info","X-Forwarded-For":["35.123.123.241"],"X-Forwarded-Host":["authenticate.example.com],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Real-Ip":["35.123.123.241"],"ip":"192.168.22.9","user_agent":"Go-http-client/1.1","req_id":"226a56b8-ac77-6b2f-04bb-3eaa4f513c67","error":"rpc error: code = Unknown desc = cache.grpc.Get error: autocache: get 427dd2648869df90 failed: autocache: empty ctx for id: 427dd2648869df90","time":"2020-05-11T23:19:17Z","message":"authenticate: session load error"}

pomerium-authenticate-669586595f-tqhn6:pomerium {"level":"info","X-Forwarded-For":["35.123.123.241"],"X-Forwarded-Host":["authenticate.example.com"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Real-Ip":["35.123.123.241"],"ip":"192.168.22.9","user_agent":"Go-http-client/1.1","req_id":"226a56b8-ac77-6b2f-04bb-3eaa4f513c67","error":"Unauthorized: rpc error: code = Unknown desc = cache.grpc.Get error: autocache: get 427dd2648869df90 failed: autocache: empty ctx for id: 427dd2648869df90","time":"2020-05-11T23:19:17Z","message":"httputil: ErrorResponse"}

---

pomerium-authenticate-669586595f-tqhn6:pomerium {"level":"info","X-Forwarded-For":["35.123.123.241"],"X-Forwarded-Host":["app1.example.com"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Real-Ip":["35.123.123.241"],"ip":"192.168.22.9","user_agent":"Go-http-client/1.1","req_id":"7e02f424-66e5-9273-80d7-cf5ce5f4c233","error":"rpc error: code = Unknown desc = cache.grpc.Get error: autocache: get 8eb82cdf233ffeb3 failed: autocache: empty ctx for id: 8eb82cdf233ffeb3","time":"2020-05-11T23:50:19Z","message":"authenticate: session load error"}

pomerium-authenticate-669586595f-tqhn6:pomerium {"level":"info","X-Forwarded-For":["35.123.123.241"],"X-Forwarded-Host":["authenticate.example.com"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Real-Ip":["35.123.123.241"],"ip":"192.168.22.9","user_agent":"Go-http-client/1.1","req_id":"7e02f424-66e5-9273-80d7-cf5ce5f4c233","error":"Unauthorized: rpc error: code = Unknown desc = cache.grpc.Get error: autocache: get 8eb82cdf233ffeb3 failed: autocache: empty ctx for id: 8eb82cdf233ffeb3","time":"2020-05-11T23:50:19Z","message":"httputil: ErrorResponse"}

pomerium-proxy-57b7486fbc-l6gxh:pomerium {"level":"warn","X-Forwarded-For":["35.123.123.241"],"X-Forwarded-Host":["forwardauth.example.com"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Original-Method":["GET"],"X-Original-Url":["http://app1.example.com/"],"X-Real-Ip":["35.123.123.241"],"X-Sent-From":["nginx-ingress-controller"],"ip":"192.168.22.9","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36","req_id":"5e62e0db-3cbd-adda-f454-d97bfb475e2c","error":"proxy: backend refresh failed: {\"Status\":401,\"Error\":\"Unauthorized: rpc error: code = Unknown desc = cache.grpc.Get error: autocache: get 8eb82cdf233ffeb3 failed: autocache: empty ctx for id: 8eb82cdf233ffeb3\",\"RequestID\":\"7e02f424-66e5-9273-80d7-cf5ce5f4c233\"}\n","time":"2020-05-11T23:50:19Z","message":"proxy: refresh failed"}
```

Previous errors:
```
pomerium-proxy-57b7486fbc-l6gxh:pomerium {"level":"warn","X-Forwarded-For":["35.123.123.241"],"X-Forwarded-Host":["forwardauth.example.com"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Original-Method":["GET"],"X-Original-Url":["http://app1.example.com/sw.js"],"X-Real-Ip":["35.123.123.241"],"X-Sent-From":["nginx-ingress-controller"],"ip":"192.168.22.9","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36","referer":"https://app1.example.com/sw.js","req_id":"ee6d044a-2118-1e66-2236-e6c5a1612acb","error":"proxy: backend refresh failed: {\"Status\":401,\"Error\":\"Unauthorized: rpc error: code = Unknown desc = cache.grpc.Get error: autocache: get 427dd2648869df90 failed: autocache: empty ctx for id: 427dd2648869df90\",\"RequestID\":\"d5a48eec-4906-8697-dadc-a813b21d13b7\"}\n","time":"2020-05-11T23:19:16Z","message":"proxy: refresh failed"}

pomerium-proxy-57b7486fbc-5xbzm:pomerium {"level":"warn","X-Forwarded-For":["35.123.123.241"],"X-Forwarded-Host":["forwardauth.example.com"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Original-Method":["GET"],"X-Original-Url":["http://app1.example.com/"],"X-Real-Ip":["35.123.123.241"],"X-Sent-From":["nginx-ingress-controller"],"ip":"192.168.22.9","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36","req_id":"4e74b5c4-fb5d-cf8a-b8b0-098f1a682cfe","reason":[],"allow":false,"expired":false,"time":"2020-05-11T22:58:37Z","message":"proxy/authorize: deny"}

pomerium-proxy-57b7486fbc-5xbzm:pomerium {"level":"info","X-Forwarded-For":["35.123.123.241"],"X-Forwarded-Host":["forwardauth.example.com"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Original-Method":["GET"],"X-Original-Url":["http://app1.example.com/"],"X-Real-Ip":["35.123.123.241"],"X-Sent-From":["nginx-ingress-controller"],"ip":"192.168.22.9","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36","req_id":"4e74b5c4-fb5d-cf8a-b8b0-098f1a682cfe","error":"Unauthorized: request denied","time":"2020-05-11T22:58:37Z","message":"httputil: ErrorResponse"}
```

Any help on this would be appreciated, happy to provide any configs where necessary.

Thanks!

**Comment by desimone** [comment] 2020-05-12 02:42
Hey @ChipWolf ,

Sorry to hear you are having issues here. Could you post a redacted form of your `config.yaml` as well?

**Comment by ChipWolf** [comment] 2020-05-12 11:29
Hi @desimone, I'm wondering if this is a regression introduced by `ingress-nginx`, similar to #442. 

config.yaml
```yaml
shared_secret: #snip
policy:
- from: https://ops.example.com
  to: http://kube-ops-view.monitoring.svc.cluster.local
  allowed_domains:
  - example.com
cookie_secret: #snip
idp_client_id: #snip
idp_client_secret: #snip
idp_service_account: #snip
forward_auth_url: https://forwardauth.example.com
```

**Comment by travisgroth** [comment] 2020-05-14 20:00
@ChipWolf what version of nginx-ingress are you running?  There was an issue with forward auth starting in v0.26.2, which was fixed in v0.29.

**Comment by ChipWolf** [comment] 2020-05-15 22:37
I'm using `ingress-nginx` considering `nginx-ingress` is now deprecated. Currently on the latest chart version.

**Comment by ChipWolf** [comment] 2020-05-15 22:37
@travisgroth I'm using `ingress-nginx` considering `nginx-ingress` is now deprecated. Currently on the latest chart version.

**Comment by ChipWolf** [comment] 2020-05-17 18:44
Hi @desimone is there any more information you need from me here? Thanks!

**Comment by mikelorant** [comment] 2020-05-21 09:40
I had exactly the same issue (everything about this issue was identical in our implementation).

The solution was due to not putting the cookie at the domain level, it was only located on the authentication host.

The solution if using Helm was as follows:

```
config:
  extraOpts:
    cookie_domain: example.org [domain one level up from auth and host needing access to]
    cookie_secure: false
```

I also added `cookie_secure` to be false as I was using the insecure mode in testing. May not be necessary but something to be aware of.

In the process I also found a bug where if using the operator, it will remove the `cookie_secure` value from the secret. This meant I had to disable the operator to make this work.

**Comment by ChipWolf** [comment] 2020-05-23 01:00
Magic @mikelorant, suddenly works with that config.
For this solution to work, I also had to remove the `kubernetes.io/ingress.class: nginx` annotation from the app's ingress which was only there originally to pass a conditional of another tool we use to list ingresses on a launchpad. It seems if I left the annotation there, Pomerium would throw 403s on the endpoint.
Happy to test any alternate solutions to this! Would be awesome to eventually see Pomerium become an ingress class so we can remove a layer of complexity and clean these annotations up a little.

**Comment by travisgroth** [comment] 2020-05-28 20:14
Just to follow up on this.  I _believe_ what you were seeing is a race condition in the operator that shipped by default with the mid 8.x.x series of the helm chart.  I have been able to sporadically reproduce on an 8.5.5 chart but not when I go up to v0.0.2 of the operator.  The operator now has better output semantics and should be race free and consistently ordered.

Essentially, the final policy coming out of the operator was probably missing a route, and we don't really have a good way of stopping redirect looping when someone isn't authorized in a forward auth scenario presently.  This goes for both a missing route _and_ an insecure scheme.  Eg, if your policy is for `https://myapp.mydomain.com` but your user goes to `http://myapp.mydomain.com` it is unauthorized, thus you will wind up in a loop.  There's been some discussion around how to mitigate this but nothing definitive at this time.

I'm not entirely clear on how @mikelorant's changes would have worked unless his issue was the scheme and the cookie tweaks persisted our cookie in spite of it, or he wound up hitting the operator in the head when it created a bad config.

@mikelorant the operator would not normally drop specific options unless it was part of the racing behavior above, or it was a new option.  I'm thinking it was the former.  If you see it continue to drop existing options on v0.0.2 or a v9 series helm chart, please do open an issue so we can take a look.  That said, you shouldn't need any workaround anymore so it may be moot.

Going to close this out.  Thanks for your patience.

**Closed by travisgroth** 2020-05-28 20:14 UTC
Labels: NeedsInvestigation
