### ISSUE TITLE
proxy: 302 redirect breaks reverse proxy

### ISSUE THREAD

**Issue by haozhou** [pomerium/pomerium#107] opened 2019-05-04 06:51 UTC
Hi,

I run into a situation that internal website uses 302/302 redirect breaks the reverse proxy.

Here's my policy file.

- from: tautulli.lab.henryzhou.com
  to: http://192.168.1.2:8181
  timeout: 10m
  allowed_users:
    - someone@gmail.com

Here's the log

11:25PM DBG proxy: request duration=19.236317 ip=x.x.x.x method=GET pomerium-email=someone@gmail.com pomerium-user=10524413789654936831 req_id=174989fa-b99c-a8b8-010c-ba03e2aa944d size=95 status=303 url=/ user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15

After the authorization, I notice the URL in the browser window changes from tautulli.lab.henryzhou.com to 192.168.1.2 which is inaccessible if I'm out of the internal network.

I wonder if the issue is caused by 302/303 redirect (of the internal website itself) or a miss configured env.

Thanks

**Comment by fightforlife** [comment] 2019-05-04 11:00
Same here for my nextcloud instance.

**Comment by desimone** [comment] 2019-05-04 19:22
Hmm, Pomerium is doing it's thing by passing along [X-Forwarded-Host](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host) so both of these apps should be working. 

@fightforlife You should be able to configure nextcloud for use with [pomerium](https://docs.nextcloud.com/server/15/admin_manual/configuration_server/reverse_proxy_configuration.html) 

@haozhou According to the [tautulli](https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#q-why-does-tautulli-not-work-with-my-reverse-proxy-setup) docs this should "just work". I wonder, would using a hostname instead of an IP work?

**Comment by haozhou** [comment] 2019-05-04 23:06
Yes. Tautulli actually has a setting to enable proxy. Unfortunately Freenas doesn’t have such setting, I wonder if there’s a way to implement rewriting rules like nginx does.

**Comment by desimone** [comment] 2019-05-08 21:24
I'm hesitant to implement something like rule rewriting as it feels like a better fit for a full fledged load balancer like HA-proxy / nginx. However, if pomerium is not passing along the right headers, that is bug and should be addressed. 

@haozhou Could you put nginx in front of pomerium [similar to this example](https://www.pomerium.io/docs/examples.html#docker) and have nginx do route-rewriting?

**Comment by jaumann** [comment] 2019-05-13 14:39
I just started experiencing this as well on my synology. It appears to work fine in the v0.0.3 release, but the v0.0.4 release breaks this.

**Comment by desimone** [comment] 2019-05-13 17:01
@jaumann Could you walk me through what you are doing when this occurs so I can try reproducing this on my end?

**Comment by jaumann** [comment] 2019-05-13 18:40
When I deploy the v0.0.4 release with the following policy, I get the issue

```
- from: sub.domain.com
  to: http://docker:1234
  allowed_users:
  - me@gmail.com
  timeout: 60m
```

I can see the lines in my logs being added
```
{"level":"debug","route":"sub.domain.com","group":"me@gmail.com","time":"2019-05-13T18:25:17Z","message":"add email"}
{"level":"info","src":"sub.domain.com","dst":"docker:1234","time":"2019-05-13T18:25:17Z","message":"proxy: new route"}
```


But then when I log in, I get a 403 error from pomerium with the following logs

````
{"level":"debug","fwd_ip":"192.168.1.1","ip":"172.17.0.1","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36","req_id":"aa216833-a634-1d39-1fce-514f99c1cdb5","error":"http: named cookie not present","time":"2019-05-13T18:30:02Z","message":"proxy: starting auth flow"}
{"level":"info","fwd_ip":"192.168.1.1","ip":"172.17.0.1","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36","req_id":"aa216833-a634-1d39-1fce-514f99c1cdb5","SigninURL":"https://authenticate.domain.com/sign_in?redirect_uri=https%3A%2F%2Fsub.domain.com%2F.pomerium%2Fcallback&response_type=code&shared_secret=XXXX&sig=XXXX&state=XXXX&ts=1557772202","time":"2019-05-13T18:30:02Z","message":"proxy: oauth start"}
{"level":"debug","fwd_ip":"192.168.1.1","ip":"172.17.0.1","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36","req_id":"aa216833-a634-1d39-1fce-514f99c1cdb5","method":"GET","url":"/","status":302,"size":504,"duration":1.843107,"pomerium-user":"","pomerium-email":"","time":"2019-05-13T18:30:02Z","message":"proxy: request"}
{"level":"error","fwd_ip":"192.168.1.1","ip":"172.17.0.1","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36","req_id":"a9ddd6ee-dde5-f105-cb2d-dc60807fc8d1","error":"http: named cookie not present","time":"2019-05-13T18:30:02Z","message":"authenticate: failed to load session"}
{"level":"warn","fwd_ip":"192.168.1.1","ip":"172.17.0.1","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36","req_id":"a9ddd6ee-dde5-f105-cb2d-dc60807fc8d1","error":"http: named cookie not present","time":"2019-05-13T18:30:02Z","message":"authenticate: authenticate error"}
{"level":"debug","fwd_ip":"192.168.1.1","ip":"172.17.0.1","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36","req_id":"a9ddd6ee-dde5-f105-cb2d-dc60807fc8d1","time":"2019-05-13T18:30:02Z","message":"authenticate: user authenticated"}
{"level":"debug","fwd_ip":"192.168.1.1","ip":"172.17.0.1","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36","req_id":"a9ddd6ee-dde5-f105-cb2d-dc60807fc8d1","method":"GET","url":"/sign_in?redirect_uri=https%3A%2F%2Fsub.domain.com%2F.pomerium%2Fcallback&response_type=code&shared_secret=XXXX&sig=XXXX&state=XXXX&ts=1557772202","status":302,"size":1045,"duration":1.456711,"time":"2019-05-13T18:30:02Z","message":"authenticate: request"}
{"level":"debug","fwd_ip":"192.168.1.1","ip":"172.17.0.1","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36","referer":"https://authenticate.domain.com/","req_id":"XXXXX","method":"GET","url":"/oauth2/callback?state=XXXXX&code=4%2FSQHdo9EDubnL8PQD7dzjFvpTcg5KqSRvfrqPvN0Flf1pR3u2xYvFESLlntBwt6nb9BavTMBNdBy3rx1c8EnUXUQ&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&authuser=0&session_state=XXXX&prompt=consent","status":302,"size":504,"duration":266.161283,"time":"2019-05-13T18:30:17Z","message":"authenticate: request"}
{"level":"debug","fwd_ip":"192.168.1.1","ip":"172.17.0.1","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36","referer":"https://authenticate.domain.com/","req_id":"XXXX","time":"2019-05-13T18:30:17Z","message":"authenticate: user authenticated"}
{"level":"debug","fwd_ip":"192.168.1.1","ip":"172.17.0.1","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36","referer":"https://authenticate.domain.com/","req_id":"XXXX","method":"GET","url":"/sign_in?redirect_uri=https%3A%2F%2Fsub.domain.com%2F.pomerium%2Fcallback&response_type=code&shared_secret=XXXX&sig=XXXX&state=XXXX&ts=1557772202","status":302,"size":1850,"duration":3.805676,"time":"2019-05-13T18:30:17Z","message":"authenticate: request"}
{"level":"debug","fwd_ip":"192.168.1.1","ip":"172.17.0.1","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36","req_id":"XXXX","code":"XXXX","state":"XXXX","RefreshToken":"XXXX","session":"XXXX","RedirectURI":"/","time":"2019-05-13T18:30:17Z","message":"session"}
{"level":"debug","fwd_ip":"192.168.1.1","ip":"172.17.0.1","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36","req_id":"XXXX","method":"GET","url":"/.pomerium/callback?code=XXXX&state=XXXX","status":302,"size":24,"duration":2.568811,"pomerium-user":"","pomerium-email":"","time":"2019-05-13T18:30:17Z","message":"proxy: request"}
{"level":"debug","fwd_ip":"192.168.1.1","ip":"172.17.0.1","user_agent":"grpc-go/1.19.0","req_id":"295b997f-6ff2-919c-506d-73f1efe31442","method":"POST","url":"/authorize.Authorizer/Authorize","status":404,"size":1935,"duration":1.064961,"pomerium-user":"","pomerium-email":"","time":"2019-05-13T18:30:17Z","message":"proxy: request"}
{"level":"warn","fwd_ip":"192.168.1.1","ip":"172.17.0.1","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36","req_id":"c588c80f-d1c5-c9bc-a3cc-4635bacb7204","error":"rpc error: code = Internal desc = transport: received the unexpected content-type \"text/html; charset=utf-8\"","time":"2019-05-13T18:30:17Z","message":"proxy: user unauthorized"}
{"level":"debug","fwd_ip":"192.168.1.1","ip":"172.17.0.1","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36","req_id":"c588c80f-d1c5-c9bc-a3cc-4635bacb7204","method":"GET","url":"/","status":403,"size":1941,"duration":9.094811,"pomerium-user":"101110710419755464402","pomerium-email":"me@gmail.com","time":"2019-05-13T18:30:17Z","message":"proxy: request"}````

**Comment by desimone** [comment] 2019-05-13 18:48
@jaumann Ahh! I think this is actually a different error. 

```
:"rpc error: code = Internal desc = transport: received the unexpected content-type \"text/html; charset=utf-8\""
```

My guess is that that the authorization service url setting is set to the external value and not the internal value. This was a breaking change between versions. 

What do your configuration variables look like (removing any sensitive data).

Does changing authroization-service-url to `https://localhost` fix it?

**Comment by jaumann** [comment] 2019-05-13 18:54
That totally did fix it. Sorry about the confusion, and thanks so much for your help!

**Comment by desimone** [comment] 2019-05-15 01:44
@fightforlife @haozhou could you provide additional context for the redirect error you are seeing? I did some [testing](https://github.com/pomerium/pomerium/issues/107#issuecomment-491904876) with httpbin and all relative 302 redirects are seem to be properly respected.

**Comment by desimone** [comment] 2019-06-01 17:19
Closing due to lack of updates. If this pops up again please do reopen.

**Closed by desimone** 2019-06-01 17:19 UTC
Labels: NeedsInvestigation
