### ISSUE TITLE
`Access-Control-Allow-Origin` and AJAX calls issue

### ISSUE THREAD

**Issue by mohsen0** [pomerium/pomerium#390] opened 2019-11-18 17:01 UTC
## What happened?

So I am trying to secure an AWS s3 website by putting pomerium in front of it.
I have setup CORs and configured the two s3 endpoints correctly, I mean it works without proxy alright.

```yaml
  - from: https://reports.example.com
    to: http://my-reports.s3-website-eu-west-1.amazonaws.com
    allowed_groups:
      - developers@example.com
  - from: https://reports-s3.example.com
    to: https://my-reports.s3-eu-west-1.amazonaws.com
    allowed_groups:
      - developers@example.com
```

The index page is a simple HTML page, which there is some javascript code that read from the XML feed in `https://my-reports.s3-eu-west-1.amazonaws.com` by invoking an ajax call 

## What did you expect to happen?

So the setup works without the proxy, but when the proxy is in place, the `Access-Control-Allow-*` headers are not set.

```
Access-Control-Allow-Methods: GET
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 0
```

and the underlying AJAX call redirected using 302 and it seems to be canceled by the browser when it tries to be authenticated by the `authenticate.example.com`.

## How'd it happen?

1. create a bucket
2. setup a website setup
3. upload https://github.com/rufuspollock/s3-bucket-listing
4. configure the pomerium as front to that bucket
5. try to access to the page.

## What's your environment like?

- Pomerium version : 0.4.0
- Server Operating System/Architecture/Cloud: kubernetes 1.12

## What's your config.yaml?

```config.yaml
  - from: https://reports.example.com
    to: http://my-reports.s3-website-eu-west-1.amazonaws.com
    allowed_groups:
      - developers@example.com
  - from: https://reports-s3.example.com
    to: https://my-reports.s3-eu-west-1.amazonaws.com
    allowed_groups:
      - developers@example.com
```

## What did you see in the logs?

browser console logs:

```logs
Access to XMLHttpRequest at 'https://reports-s3.example.com/?delimiter=/&prefix=reports/' from origin 'https://reports.example.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

[reports.example.com.har.zip](https://github.com/pomerium/pomerium/files/3859780/reports.example.com.har.zip)

## Additional context

https://github.com/pomerium/pomerium/pull/387

**Comment by desimone** [comment] 2019-11-19 06:23
@mohsen0 Thank you for the detailed issue!

Does enabling `cors_allow_preflight` help? [docs](https://www.pomerium.io/configuration/#policy)

**Comment by mohsen0** [comment] 2019-11-19 08:00
No I have tried that

**Comment by desimone** [comment] 2019-11-19 18:43
When you tried adding `cors_allow_preflight: true` to those handlers, you saw the same error?

That setting should be allowing the preflight requests to pass-through to to your application. 🤔

**Comment by mohsen0** [comment] 2019-11-20 17:15
So I enabled the `cors_allow_preflight: true` too, and nothing changed, In the developer tools, I could see that there is no OPTION call, but there is GET AJAX call that gets redirected with 302 and since there is not `Access-Control-Allow-*` set, it fails.
I attached HAR file with `cors_allow_preflight` enable.
[reports.example.com-1.har.zip](https://github.com/pomerium/pomerium/files/3870425/reports.example.com-1.har.zip)

**Comment by desimone** [comment] 2019-11-21 05:00
Thanks @mohsen0  I will investigate.

**Comment by mohsen0** [comment] 2019-11-22 10:53
Loading Kibana this issue happens for this call which is weird. Since other AJAX calls do have their `Access-Control-Allow` set behind the proxy. only this call gets redirected.
it seems to be the first AJAX call on the page.
`GET https://kibana-dev.example.com/ui/favicons/manifest.json`

**Comment by mohsen0** [comment] 2019-12-06 10:02
Any new discovery on this issue?

**Comment by desimone** [comment] 2019-12-06 20:03
@mohsen0 I'm not exactly sure what's going on from the logs and the har file alone.

Do you mind posting more context both in the form of `har` and both your application and pomerium logs?  If sensitive, feel free to email me bdd@pomerium.io. `CORs` issues are an absolute pain to debug and isolate.

**Comment by commixon** [comment] 2019-12-12 15:31
Hi everyone. Just wanted to say that we have the exact same problem.
We have one SPA portal and one api backend. They are exposed as follows:
```
     -  from: https://spa.my.root.domain
        to: http://spa.pomerium.svc.cluster.local
        allowed_domains:
          - domain.co
        cors_allow_preflight: true
     -  from: https://api.my.root.domain
        to: http://api.pomerium.svc.cluster.local
        allowed_domains:
          - domain.co
        cors_allow_preflight: true
```

When visiting each one of those separately everything works fine. But when the JS code in our SPA tries to perform AJAX calls, we get the error mentioned in the previous comments:

`Access to XMLHttpRequest at 'https://api.my.root.domain/api/v1/search?page=1&name=' from origin 'https://spa.my.root.domain' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by desimone** [comment] 2019-12-12 19:05
Thanks for the info @commixon ; I've been able to reproduce the issue and this is my top priority to fix when I return. 

@mohsen0 / @commixon Does this docker image `pomerium/pomerium:ISS409v1` mitigate the issue?

**Comment by commixon** [comment] 2019-12-13 07:38
Hey @desimone , sadly this does not mitigate the issue.
The error on the XMLHttpRequest is the same, `No 'Access-Control-Allow-Origin' header is present on the requested resource.`

If ti helps, pomerium-proxy's logs seems to be a little different. In the `ISS409v1` case I get: 
```
DBG proxy: authenticate session error="internal/sessions: session is not found"...
DBG proxy: AuthorizeSession error="Unauthorized: internal/sessions: session is not found"...
INF httputil: ErrorResponse error="Unauthorized: internal/sessions: session is not found"...
```

With the `v0.5.2` image I only get:
```
DBG proxy: authenticate session error="internal/sessions: session is not found"
```

**Comment by mohsen0** [comment] 2019-12-13 10:06
Hi, I can confirm, it didn't fix it.

**Comment by commixon** [comment] 2019-12-17 13:40
Hey @desimone  if you have started working on it in a branch/fork and want a second set of eyes I'm pretty happy to help. I am also available to look at it if you have no time, in this case if you pointed me to the correct direction that would be great since I am just getting familiar with the project as we speak.

**Comment by desimone** [comment] 2019-12-17 17:24
@commixon thanks for the offer of help I appreciate it! I started working through a fix but would totally welcome another set of eyes and/or chat about the approach that makes the most sense. Would you be free to jump in the dev channel on slack to chat synchronously?

**Comment by desimone** [comment] 2019-12-19 18:47
@mohsen0 I took another look at this and your logs / har file. 

To clarify, you are trying to make an XHR request from one pomerium protected resource to another ( https://reports.example.com --> https://reports-s3.example.com ) where you have all your javascript/frontend/SPA bits on one route, and its backend /api sitting on another? 

What's a bit confusing to me based on your `har` file (which is super helpful thank you) is:

1. the `_pomerium` cookie set on `https://reports.example.com` actually looks like the global encrypted cookie I would expect to see set on your authenticate endpoint. Do you mind posting your full (redacted) config.yaml and policy?
2. It looks like you are able to login initially to `https://reports.example.com` is that right?
3. It's the subsequent XHR request that fails from `https://reports.example.com` to the api backend `https://reports-s3.example.com`. 

If so, this actually makes sense. While you _are_ authenticated to `reports` using a same-site bound JWT cookie that session does not apply to and will not be passed along to `https://reports-s3.example.com` OR `authenticate.example.com` (which the XHR is probably 302'ing you to) because of two things:

1. Pomerium sessions ared scoped to domain of the managed route. `https://reports.example.com` and `https://reports-s3.example.com` and require two different auth flows. 
2. XHR requests only pass along session cookies by default (I believe!) to the [same-origin](https://en.wikipedia.org/wiki/Same-origin_policy) as the request. 


What I don't understand is why the application is not responding to CORS preflight requests if you have your application configured and have the `cors_allow_preflight` bit flipped. The cors middleware should be passing through any preflight requests:

https://github.com/pomerium/pomerium/blob/a29ae6428fcdb1f073e42d751d5ee15008fa4390/internal/middleware/cors.go#L12-L26

Is there anyway to get both of these routes under the same managed domain so they can share a credential?

**Comment by desimone** [comment] 2019-12-31 00:05
@commixon / @mohsen0 : this should be fixed on master. `docker pull pomerium/pomerium:master` via #438

**Closed** 2019-12-31 04:53 UTC
Labels: accepted, bug
