### ISSUE TITLE
github idp allow_groups expects github internal team id

### ISSUE THREAD

**Issue by kernel164** [pomerium/pomerium#788] opened 2020-05-27 04:47 UTC
## What happened?

for github idp if policy is set as allow_groups=["@org/team"], it doesn't work

but if I set allow_groups=["teamid-number"] e.g allow_groups=["6523484"] it works.

## What did you expect to happen?

policy set as allow_groups=["@org/team"] should work

**Comment by desimone** [comment] 2020-05-27 15:43
Dupe of #573

**Closed by desimone** 2020-05-27 15:43 UTC
