### ISSUE TITLE
identity/github: Pomerium uses teams' ids instead of names

### ISSUE THREAD

**Issue by leshik** [pomerium/pomerium#627] opened 2020-04-22 07:32 UTC
With the Github identity provider, It's a bit weird to specify numeric team ids in `allowed_groups` option to filter users. While I understand it helps to map Github teams to the existing Pomerium `allowed_groups` option and to keep these groups unique throughout all organizations, but shouldn't it use teams' names instead, plus some `allowed_orgs` option just for Github?

**Comment by desimone** [comment] 2020-04-22 15:24
Hey @leshik thanks for the feedback. This is a tricky one. While agree that using number team ids is less than the ideal operator user experience, I think that concern is counter balanced with wanting an immutable ID that can be handled consistently between provider configurations so we don't have different group mappings for each provider.


Possible dupe of 
https://github.com/pomerium/pomerium/issues/573

**Comment by desimone** [comment] 2020-05-27 15:44
Closing in favor of keeping discussing at #573

**Closed by desimone** 2020-05-27 15:44 UTC
