### ISSUE TITLE
cookie do not contain full jwt assert

### ISSUE THREAD

**Issue by psychomelet** [pomerium/pomerium#1402] opened 2020-09-12 10:40 UTC
The `X-Pomerium-Jwt-Assertion` is correct by when try to extract the same info from cookie, the jwt decoded json shows the information as follows without email or user identity info inside.

```
{
  "aud": [
    "authenticate.auth.corp",
    "httpbin.auth.corp"
  ],
  "exp": 1600336519,
  "iat": 1599904827,
  "iss": "auth.corp",
  "jti": "adab2453-e569-47da-a75a-97c71a4fea02",
  "nbf": 1599904227,
  "programatic": false,
  "sub": "ff56d9bc-589d-4d89-a268-a13c004ecee5",
  "ver": "7610de79-84ba-4653-889a-22a2d4054796"
}
```

**Comment by psychomelet** [comment] 2020-09-12 11:53
The problem exists in v0.10 version and works correctly in v0.9.1 before, should caused by latest change.

**Comment by desimone** [comment] 2020-09-14 22:00
Hi @psychomelet , 

Pomerium's JWT cookie / token is meant to be internal to Pomerium which is why we strip it before it hits the upstream app. I highly suggest using the `X-Pomerium-Jwt-Assertion` instead. Can you tell me a bit more about how you are using the pomerium cookie? 

Thanks!

**Comment by psychomelet** [comment] 2020-09-15 06:22
We use pomerium with an SPA application:
1. request goes to domain1.corp.com, which is static frontend site, then the javascript will read the cookie and use it for auth with the api server hosted in domain2.corp.com.
2. the api server will receive the jwt token and verify it with secret key.

**Comment by psychomelet** [comment] 2020-09-15 06:28
Previously discussed solution in issue https://github.com/pomerium/pomerium/issues/511 and https://github.com/pomerium/pomerium/issues/512

**Comment by psychomelet** [comment] 2020-09-15 06:37
It's pretty common to have an infrastructure to hosting `frontend + api` in different domains, maybe we can make it an option to at least let user decide if it's enabled?

**Comment by psychomelet** [comment] 2020-10-22 08:46
Any updates on this issue, the problem prevents us from upgrading pomerium.

Maybe we can add an option in config to bring back the feature when we're thinking about it?

**Comment by desimone** [comment] 2020-11-12 02:30
Hey @psychomelet  

I am reluctant to support this functionality as the pomerium session cookie  was never intended to be used this way; unfortunately, if using forward authentication we don't control what cookies are stripped or not so I can see how you ended up thinking it was okay to use for this purpose. 

As a work around, would it be possible to use the recently introduced jwt endpoint instead? 

- https://github.com/pomerium/pomerium/issues/1369#issue-692466285
- https://github.com/pomerium/pomerium/pull/1446

**Comment by desimone** [comment] 2020-11-12 02:33
(closing because this does feel like a dupe of #1282 but happy to continue the discussion there)...

**Closed by desimone** 2020-11-12 02:33 UTC
Labels: NeedsDecision, thinking
