### ISSUE TITLE
pomerium-cli/k8s: Document an edge case with having to manually invalidate Pomerium tokens

### ISSUE THREAD

**Issue by sherifkayad** [pomerium/pomerium#2263] opened 2021-06-02 17:27 UTC
**Is your feature request related to a problem? Please describe.**

As per the discussion on https://github.com/pomerium/pomerium/issues/1201#issuecomment-852099091

_Disclaimer:_ This issue is more or less about documentation.

After some hours of investigation, I was curious how one could invalidate sessions / clear tokens created by the Pomerium CLI and where it basically caches tokens generated for further use until expiry.

Currently there's an edge case that needs to be mentioned in the documentation that if a user terminates his/her Pomerium session from the browser or if the Pomerium pods are terminated on Kubernetes (while using a non-persistent Databroker e.g. memory or Redis without persistence) the session of course is lost and browser users are forced to re-login through the IdP. This scenario creates an issue with the `pomerium-cli` in conjunction with Kubernetes; as it looks up a cached token and attempts to use it for authentication. Of course the auth will fail and the user will NOT be forced to re-login. Instead an error occurs e.g.:
```
couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
```

**Describe the solution you'd like**
There should a clear documentation for the Pomerium users that such edge case exists and facing it means that users have to manually delete their Pomerium `cache` directory. Of course depending on the OS that could be:
- `/c/users/USER/AppData/Roaming/pomerium-cli/cache` for Windows
- `~/.config/pomerium-cli/cache` for Linux

**Describe alternatives you've considered**
There are no alternatives IMHO because even if one uses persistent storage for the sessions on the server side, a logout from the browser can still cause this case here.

**Explain any additional use-cases**
N.A.

**Additional context**
N.A.

**Comment by paddycarey** [comment] 2021-06-18 16:18
I'm seeing similar issues in some of my clusters when pomerium pods are restarted, happy to help debug if i can be of any assistance.

**Comment by sherifkayad** [comment] 2021-06-18 22:01
@paddycarey in my view that's not really a debugging topic .. the easiest solution would be documenting that somehow in the Pomerium official docs as a note / limitation / whatever that people need to be aware of and can solve by clearing their caches.

Ultimately I would love to see (maybe in a future release) the ability of Pomerium to clear its own caches shall this scenario happens and re-attempt an auth automatically.

**Comment by sherifkayad** [comment] 2021-06-18 22:01
@travisgroth what's your take on that?

**Comment by travisgroth** [comment] 2021-07-02 21:33
I think we can provide a command to manually clear out the cache, wherever it may be.  That seems pretty reasonable.

As far as automatically taking corrective action...the tricky thing about the k8s integration is that you have performance/UX and cache at odds with detecting this type of scenario.  We cache your credentials for as long as your initial session is valid, but the k8s exec interface doesn't give our plugin feedback if the remote request fails.  In order to detect this on our own, we'd need to artificially depress the cache interval and either run an extra upstream request to check if the credentials are still valid OR actually pop up browser flow again.  Neither is optimal as we're checking for a corner case every time our credentials helper is executed.

Finally, the error message should be improved in `v0.14.6`.  We detect the `Accept` type for applications which won't handle a 302 correctly.  The new result of a bad/stale token:

```
% k get pods
error: You must be logged in to the server (the server has asked for the client to provide credentials)
```

Though not ideal, it at least points you at a credentials issue.

**Comment by sherifkayad** [comment] 2021-07-02 22:02
@travisgroth First of all thanks for the detailed analysis and conclusion you mentioned.

In my view:
- A command to clear the cache is a perfect starter! Definitely better than the current "workaround" of deleting that manually.
- Great stuff with the improved message. However, if newer versions of the Pomerium CLI are able to detect bad tokens / credentials, why is the browser flow a bad UX from your point of view? 🤔 .. won't that be just fine to re-initiate the browser login flow and get the user a new token? .. doing so might eliminate the need for a cache invalidation command.

What do you think?

**Comment by travisgroth** [comment] 2021-07-03 12:24
> Great stuff with the improved message. However, if newer versions of the Pomerium CLI are able to detect bad tokens / credentials

Just to clarify, this isn't from Pomerium's client side code.  The proxy is responding 401 and kubectl recognizes that as a credentials issue.  The credentials plugin only knows if (a) it has a token already (b) the token is expired.  Credentials helpers unfortunately don't get any feedback from their invoker on whether there is a problem.

> why is the browser flow a bad UX from your point of view? 🤔 .. won't that be just fine to re-initiate the browser login flow and get the user a new token? .. doing so might eliminate the need for a cache invalidation command. Maybe this is not Technically feasible because the Pomerium CLI doesn't get direct feedback about the kubectl result?

See first point.  The problem is we wouldn't _know_ when to do it.  The most extreme version would be popping up a browser for every invocation of the credentials command, which is not great.  Anything less frequent than "always", but more frequent than the token expiration, would be a guess and lead to extra browser tabs opening for no particular reason most of the time.  Whatever interval we pick could still be too infrequent to prevent errors in the cli if you _just_ logged out.  I don't really see a good way to do this.

> Assuming that the previous point isn't feasible, why doesn't the Pomerium CLI validate the token against the Pomerium server prior to submitting it to the kubectl? Again why did you mention that this might be bad UX?

This would mean every command pays the overhead of a round trip request to the API server to pre-check the credentials.  Though not as bad as opening a browser tab, it would make every invocation of the credentials command 2x slow in the best case.  I'm not sure it's worth doing that for every command just in case you've logged out.

Will discuss with the broader team to see if there's something else we can do here, but I suspect any optimization still leaves you with stale credentials for _some_ period of time after logging out with no practical way to knowing.  Hopefully the improved error message and the proposed helper command makes this less of an issue.

**Comment by sherifkayad** [comment] 2021-07-03 12:37
@travisgroth got ya .. thanks again for the detailed arguments. In that case I would agree with you completely; the helper command to clear the cache and the improved error message would be the best option .. at least for the time being.

**Comment by travisgroth** [comment] 2021-07-20 15:59
Closing in favor of #2378 with a clear feature request.

**Closed by travisgroth** 2021-07-20 15:59 UTC
Labels: enhancement
