### ISSUE TITLE
Dashboard can't evaluate field GetClaim

### ISSUE THREAD

**Issue by MattiasGees** [pomerium/pomerium#1558] opened 2020-10-29 10:13 UTC
## What happened?

When visiting https://example.com/.pomerium I am getting an internal 500 server error. I wanted to test the new claims future that has been introduced for policy checking.

<img width="768" alt="Screenshot 2020-10-29 at 10 07 30" src="https://user-images.githubusercontent.com/2216724/97554425-a6f58e00-19ce-11eb-8a7a-c9714a734545.png">

## What did you expect to happen?

To see my user details 

## How'd it happen?

1. Visited  https://example.com/.pomerium

## What's your environment like?

Running a deployed HELM chart in Kubernetes with the images pointing to master

## What's your config.yaml?

```values.yaml
config:
  rootDomain: example.com
  policy:
    - from: https://web-test.example.com
      to: https://web-test.example.com
      allowed_idp_claims:
        teams:
          - test-group

authenticate:
  idp:
    provider: oidc
    clientID: <>
    clientSecret: <>
    url: <>
    scopes:
    - openid
    - email
    - groups

forwardAuth:
  enabled: true

image:
  tag: master
  pullPolicy: Always
```

**Comment by calebdoxsey** [comment] 2020-10-29 14:14
Oops. I broke this because I forgot this method was used in the dashboard template. I'll work on a fix.

**Comment by calebdoxsey** [comment] 2020-10-29 16:49
@MattiasGees I just merged a change that should fix this in master. Apologies for the regression.

**Closed** 2020-10-29 16:49 UTC

**Comment by MattiasGees** [comment] 2020-10-30 09:40
Thanks, tested it and it works
