### ISSUE TITLE
proxy doesn't pass liveness probe

### ISSUE THREAD

**Issue by rspier** [pomerium/pomerium#1336] opened 2020-08-26 04:01 UTC
## Summary

pomerium proxy (launched via helm charts) sometimes fails to successfully start due to failing liveness probe.

## Details

```Events from kubectl describe

Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  <unknown>            default-scheduler  Successfully assigned pomerium/pomerium-proxy-84bb9dc8ff-lhcd2 to kw4
  Normal   Pulled     90s (x3 over 2m29s)  kubelet, kw4       Container image "pomerium/pomerium:v0.10.1" already present on machine
  Normal   Killing    90s (x2 over 2m)     kubelet, kw4       Container pomerium failed liveness probe, will be restarted
  Normal   Created    89s (x3 over 2m29s)  kubelet, kw4       Created container pomerium
  Normal   Started    89s (x3 over 2m28s)  kubelet, kw4       Started container pomerium
  Warning  Unhealthy  81s (x7 over 2m21s)  kubelet, kw4       Readiness probe failed: Get https://10.42.4.131:443/ping: dial tcp 10.42.4.131:443: connect: connection refused
  Warning  Unhealthy  80s (x7 over 2m20s)  kubelet, kw4       Liveness probe failed: Get https://10.42.4.131:443/ping: dial tcp 10.42.4.131:443: connect: connection refused
```

```Config
address: ":443"
grpc_address: ":443"
certificate_file: "/pomerium/cert.pem"
certificate_key_file: "/pomerium/privkey.pem"
certificate_authority_file: "/pomerium/ca.pem"
authenticate_service_url: https://authenticate.int.mydomain.com
authorize_service_url: https://pomerium-authorize.pomerium.svc.cluster.local
cache_service_url: https://pomerium-cache.pomerium.svc.cluster.local
idp_provider: google
idp_scopes: 
idp_provider_url: 
cookie_secret: RDREDACTED=
shared_secret: FPREDACTED=
idp_client_id: REDACTED.apps.googleusercontent.com
idp_client_secret: REDACTED


databroker_storage_type: memory    
policy:
  - allowed_users:
    - myaccount@gmail.com
    - otheraccount@other.org
    from: https://prometheus.int.mydomain.com
    to: http://prometheus.monitoring.svc.cluster.local:9090
  # and a bunch more nearly identical except for from: and to: allowed-users blocks
```

Log from a failed run: [p.log](https://github.com/pomerium/pomerium/files/5127534/p.log)

This only affects `pomerium-proxy`:

```
$ kubectl get pod
NAME                                     READY   STATUS             RESTARTS   AGE
alpine-665ff6b94c-77v9n                  1/1     Running            0          9d
pomerium-authenticate-78595ddf64-nrdmg   1/1     Running            0          24h
pomerium-authorize-54f48c9fc4-r2ks5      1/1     Running            0          24h
pomerium-cache-56f4649b8-fpzt5           1/1     Running            0          24h
pomerium-proxy-84bb9dc8ff-lhcd2          0/1     CrashLoopBackOff   6          5m26s
```

## Environment

Kubernetes v1.17.9 on Bare Metal (via Rancher)

## Thoughts 

I had initially speculated that the workaround was to make the liveness probe more relaxed, but I think that was just a placebo as it would often trigger the pod to be deployed on a different machine.  But I've had both success and failure on the same machine, so there may be something to it.

The concerning bit is there's nothing obvious in the logs.  "Can't bind to :443" or similar.

When debugging this last night, I tried more detailed logs, but they didn't have much that was obviously helpful.

```
POMERIUM_DEBUG: true
LOG_LEVEL: debug
```

**Comment by desimone** [comment] 2020-08-26 15:29
Hi @rspier thanks for making an issue.

Nothing obvious is jumping out at me other than that the warm-up process is taking way longer than I would expect (on most hardware I see this <~seconds). Can you tell me a bit more about the baremetal environment this is running on? 

Thanks!

**Comment by rspier** [comment] 2020-08-26 15:49
It's beefy hardware in a packet.com cluster.    (They're awesome, fwiw.)

2 x Intel Xeon E5-2650 v4 @2.2GHz
256GB RAM

* It's not overloaded in any obvious manner.  A lot of idle CPU time.  
* Flannel networking.

**Comment by desimone** [comment] 2020-08-27 00:42
@rspier
Yeah, that's _definitely_ a beefy enough setup! What's especially peculiar is that:

1. this is happening on just the proxy service; the others also use envoy so I'm not sure that's the cause 
2. It sometimes works?

Some ideas.

1. Does commenting out these two lines of your config help?

```diff
+#address: ":443"
+#grpc_address: ":443"
```

2. Do you mind also posting the `debug` level'd logs to see if there's anything buried in there? 
3. Are you using auto-cert by any chance?
4. Would you be able to post a success start vs an unsuccessful start's logs?

Thanks !

**Comment by travisgroth** [comment] 2020-08-27 14:10
@rspier can you also please share your helm values?

**Comment by rspier** [comment] 2020-08-27 15:21
Here's the helm values:

[pom-values.yaml.txt](https://github.com/pomerium/pomerium/files/5137308/pom-values.yaml.txt)

**Comment by rspier** [comment] 2020-08-27 15:30
Debug log:

[pom-debug.log.txt](https://github.com/pomerium/pomerium/files/5137352/pom-debug.log.txt)

**Comment by travisgroth** [comment] 2020-08-27 15:52
Could you try taking out the `resources` spec in the chart values?  I wouldn't expect that to be an issue, but it's worth verifying.

**Comment by rspier** [comment] 2020-08-27 16:28
Taking it out seemed to make things worse, as one of the authorize jobs also started failing.

Going the opposite direction worked the first time:

```
resources:
  limits:
    cpu: 500m
    memory: 1000Mi
  requests:
    cpu: 100m
    memory: 300Mi
```

The original `cpu: 100m` limit came from the sample values.yaml in the repository.

A little bit of experimentation.  `cpu: 200m` limit took about 55 seconds to start.  `cpu: 400m` limit took ~20 -30 seconds in multiple runs.  (There's fuzz in there because of the liveness probe interval.)  `cpu: 300m` took ~38 seconds.  `cpu: 500m` consistently starts in an acceptable time.

CPU starvation is definitely looking like a likely culprit.  Our cluster is small (and not heavily loaded) that we'd not been doing very active management.

**Comment by travisgroth** [comment] 2020-08-27 19:29
>Taking it out seemed to make things worse, as one of the authorize jobs also started failing.

Depending on the state of your install, you can get a brief crash loop due to some interdependencies between services.  It should resolve itself if you give it the opportunity.  If you have multiple replicas and are upgrading, you won't see the behavior.

> cpu: 500m consistently starts in an acceptable time.

Okay, this is interesting though not completely shocking.  I would recommend a gracious `limits` (1) and low `requests` (100m).  We haven't profiled startup CPU but there is a lot of configuration generation/loading happening, and that must need a reasonable amount of CPU time to get through.  Once you're online, I would expect incremental changes to only cause light CPU usage, but can't say for certain at this time.  

Keep in mind, you also need to account for actual traffic handling across the components - authorize and proxy being the hot path.  We do have an HPA option but I wouldn't use less than 1 or 2 CPUs per pod before scaling out.

Going to close this out.

**Closed by travisgroth** 2020-08-27 19:29 UTC
Labels: NeedsInvestigation, WaitingForInfo
